[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "npm install --production=false",
  "cd client && npm install",
  "cd client && npm run build"
]

[start]
cmd = "node server/index.js"
