[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "npm ci --omit=dev || npm install",
  "cd client && npm ci || npm install",
  "cd client && npm run build"
]

[start]
cmd = "node server/index.js"
